### PR TITLE
Move to npm org tweaks

### PR DESCRIPTION
**Pull request by vladucu**
### What's here

- updates to use scoped package in both `package.json` and `index.js`
- updates exports/imports to use scoped package

NOTE: Until now everything worked because we didn't changed `index.js` name, with this we will break imports and stuff....however we need to do this, since otherwise newly generated stuff will use scoped name, but import won't resolve because it will still use un-scoped name

### CODE REVIEW

**Comment by andrewpye** [comment]
eep, failed on Travis... _I take back what I just said_ 😜

**Comment by vladucu** [comment]
meh, I guess I was the first one that run into this
waiting for travis...doesn't seems like our issue

**Comment by andrewpye** [comment]
Looks like a node version incompatibility with `broccoli-svg-optimizer` 😬 

image

**Comment by vladucu** [comment]
yeap, but we didn't touched that and it worked so far....checking more

**Comment by andrewpye** [comment]
Yeah... thanks 🙂

**Pull request merged**
