### PR TITLE
Fix action item actions event bubbling

### PR DESCRIPTION
**Pull request by tomnez**
Fix for https://github.com/smile-io/ember-polaris/issues/162

### CODE REVIEW

**Comment by tomnez** [comment]
Added this to `dev` since we're closing in on the v2.11.0 branch, I figure it can be a part of that release rather than go through a release cycle for this fix and then another one a couple days later after v2.11.0.

Let me know if anyone thinks I should repurpose this to go straight to `master` for a quick bugfix release instead.

**Comment by vladucu** [comment]
I think we can likely follow Ember suite and port this to the next 1.x+ version if anybody needs it...no biggie

**Comment by vladucu** [comment]
but yeah, a test would be nice

**Comment by tomnez** [comment]
@vladucu added a test and resolved conflicts, will merge once it passes 🕺

**Pull request merged**
