### PR TITLE
Update smile linting & code formatting tools

### PR DESCRIPTION
**Pull request by sivakumar-kailasam**
Whenever we need to update eslint config for ember apps/addons, we need to update it in [eslint-plugin-smile-ember](https://github.com/smile-io/eslint-plugin-smile-ember) & release it.

Other linting configs can be updated in our [ember-styleguide](https://github.com/smile-io/ember-styleguide) project & once released, we can run `yarn setup-smile-styleguide` to update relevant configs & packages.

### CODE REVIEW

**Comment by andrewpye** [comment]
@sivakumar-kailasam could you look into fixing up the couple of test errors on CI here please? 🙏

**Comment by andrewpye** [comment]
Actually @sivakumar-kailasam, I just saw that this PR is based on @tomnez's https://github.com/smile-io/ember-polaris/pull/320 where these failures seem to have come from, so please ignore 😝

**Comment by sivakumar-kailasam** [comment]
Oh forgot to mention that 😅 I'm working through fixing tests on a different branch that'll hopefully solve those errors.

**Comment by tomnez** [comment]
Merging this and then @sivakumar-kailasam can just PR the tests into the base 💃

**Pull request merged**
