### PR TITLE
Stop popover content from jumping around

### PR DESCRIPTION
**Pull request by sivakumar-kailasam**
Fixes what's seen in the recording below,

recording

### CODE REVIEW

**Comment by sivakumar-kailasam** [comment]
Yep, tested on edge 17, safari, firefox & chrome.

**Comment by vladucu** [comment]
> Yep, tested on edge 17, safari, firefox & chrome.

🚀

**Comment by sivakumar-kailasam** [comment]
Today is a strange day. Random things are failing in other ember try scenarios 😭

**Comment by sivakumar-kailasam** [comment]
Looks like Travis needed to relax over the weekend to allow the tests to pass again 🙂

**Pull request merged**
